# Generated by Django 5.1 on 2024-08-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveLeads',
            fields=[
                ('currenttimemillis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('platform', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CallList',
            fields=[
                ('currenttimemillis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('platform', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewLeads',
            fields=[
                ('currenttimemillis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('platform', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('attempt', models.IntegerField(default=0)),
            ],
        ),
    ]
