FROM python:latest

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    wget \
    software-properties-common \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install \
    numpy \
    django \
    firebase-admin \
    tqdm \
    djangorestframework

EXPOSE 8000

CMD ["/bin/bash"]